server.port=8081

spring.application.name=microsservico-usuarios

# Configuração do Banco de Dados em Memória (H2)
spring.datasource.url=jdbc:h2:mem:db_usuarios
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

grpc.client.microsservico-autenticacao.address=static://localhost:9090

grpc.client.microsservico-autenticacao.negotiation-type=plaintext

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/